// console.log(document.body);
// console.dir(document.body);
// document.body.style.background = "blue";
// console.dir(document.body.childNodes[2].innerText= "abcd");       
let heading = document.getElementById("heading");
console.dir(heading);
let heading2 = document.getElementsByClassName("heading2");
console.dir(heading2);
let para = document.getElementsByTagName("p");
console.dir(para);
let elements = document.querySelector("p");
console.dir(elements);
let allelements = document.querySelectorAll("p");
console.dir(allelements);
let allelements1 = document.querySelectorAll(".dd");
console.dir(allelements1);
let allelements2 = document.querySelectorAll(".dd");
console.dir(allelements2);
console.log(heading.tagName);
let allelements4 = document.querySelector("div").children;
console.dir(allelements4);
div = document.querySelector("div");