// const student  ={
//     fullname :"sh",
//     marks :94.4 ,
//     printmarks: function() {
//  console.log("marks = ", marks);
//     },


// };
 const employee = {
    calctax()
    {
console.log("tax rate is 10%");
    }
    // ,
    // calctax2 : function(){
    //     console.log("tax rate is 10%");
    // }
 };
 const karanarjun  = {
    salary : 50000,
 };

 karanarjun.__proto__ = employee ;
